### ISSUE TITLE
Footer elements alignment

### ISSUE THREAD

**Issue by matachi** [jbub/ghostwriter#21]
Hi,

I noticed that the site title and scroll-to-top button aren't that well aligned in the footer:

![screen shot 2017-01-06 at 23 20 42](https://cloud.githubusercontent.com/assets/980838/21735042/049e6268-d467-11e6-88f4-25c2b047d631.png)

I looked into it quickly, and didn't come up with any fix. Maybe you have better luck. Otherwise I will try to poke at it again when I have time.

**Comment by jbub** [comment]
Hey, do you want the scroll to top button to be centered ?

**Comment by matachi** [comment]
I believe it should be centered horizontally on the screen, placed below the logo. I think that's consistent with how the header behaves, where the social media icons are centered below the site's title. However, now the footer looks weird in how the site's title and the button are left-aligned like in the picture.
