### ISSUE TITLE
Google Analytics implemented?

### ISSUE THREAD

**Issue by jrosen48** [jbub/ghostwriter#32]
Hi, thanks for such a great theme. Is Google Analytics implemented? In the template file, of course, there is the `googleAnalytics` field, but if I understand correctly there need to be changes to the template field as well (as described [here](https://discourse.gohugo.io/t/implementing-google-analytics-in-hugo/2671/3). I ask only because I added a Google Analytics tracking code, correctly, I hope, but don't seem to see it registering activity yet. Thanks for your consideration of this!

**Comment by jbub** [comment]
Hello, you just have to set `googleAnalytics` in your site config to your `UA` code, and you should be all set. 

As you can see we already include the analytics template here if you set your code: https://github.com/jbub/ghostwriter/blob/master/layouts/partials/header.html#L22

You should see this code just after the `<body>` tag:

```html
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXX-XXX', 'auto');
ga('send', 'pageview');
</script>
```

**Comment by jrosen48** [comment]
Thanks so much. So, I added it to my `config.toml` file ([here](https://github.com/jrosen48/homepage-source/blob/master/config.toml)), but don't appear to have any updates in Google Analytics. Thank you again - do you have any suggestions for what I may be doing wrong?

**Comment by jbub** [comment]
@jrosen48 Can you give me the url to your generated website, i can check if it is correctly generated. Thanks

**Comment by jrosen48** [comment]
Sure thing - it is [https://jrosen48.github.io/](https://jrosen48.github.io/)

**Comment by jbub** [comment]
Okay so there is no google analytics javascript on your website. I see that you are using `0.18.1` version of hugo. So i downloaded your website code, used hugo `0.18.1` to generate it on my localhost and looked at the `../jrosen48.github.io` directory, it contains the google analytics javascript:

```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-43032207-1', 'auto');
ga('send', 'pageview');
</script>
```

So the mystery is, how are you generating your website ? Are you sure you are using the right directory ? Can you try generating on your localhost and see if in `index.html` you have the right google analytics javascript ? Please provide the steps you using to generate your blog. Thank you!

**Comment by jrosen48** [comment]
Ah hah, just one quick question, I will try your other suggestions as well, but is this possibly related to the need to have the javascript dependencies installed? Thanks again!

**Comment by jbub** [comment]
If you mean javascript dependencies from the theme, no they are not needed, they are only needed if you want to customize the theme SCSS and the compile to CSS.

**Comment by jrosen48** [comment]
Ok, thanks, yes, that is what I had in mind. I am generating my website using [Blogdown](https://github.com/rstudio/blogdown). I will try these other suggestions soon.

**Comment by jrosen48** [comment]
Worked! thanks
