### ISSUE TITLE
Is it possible to have dropdown menu ?

### ISSUE THREAD

**Issue by janeshdev** [jbub/ghostwriter#33]
Hi I want to have the dropdown menu on my site using your theme. I want something like following. 
![image](https://user-images.githubusercontent.com/3325086/28288945-c6aa5b62-6af5-11e7-92c5-2c0ef9f5f29e.png)
 
My config.toml file looks like following:

baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Jd's Notebook"
paginate = 10
theme = "ghostwriter"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/" 
[[menu.main]]    
    name = "Github Configuration"
    url = "/github-configuration/index.html"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/janeshdev"
[[menu.main]]    
    name = "Github"
    url = "https://github.com/janeshdev"
[[menu.main]]    
    name = "DSI Posts"
    url = "/tags/dsi/"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[params]
    description = "Janesh Devkota's personal notebook"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
I don't want to change the position of the menu. It will be the default menu that is on the top of the website.

In simple words, I was wondering if I could add few items under About in the menu.

**Comment by jbub** [comment]
Hey, currently only top level menu items are supported :(
