### ISSUE TITLE
Pygments, responsive

### ISSUE THREAD

**Issue by dazinator** [jbub/ghostwriter#37]
If you use `pygmentize` for server side syntax highlighting, currently this overflows horizontally on the page.

![image](https://user-images.githubusercontent.com/3176632/28935358-379b4f46-787c-11e7-8eed-69369e4246d7.png)

If its a simple fix i'll submit a PR

**Comment by jbub** [comment]
Hey @dazinator, im not currently using pygmentize. Feel free to submit a PR. Thank you!
