### ISSUE TITLE
Some questions about author, slug and documentation

### ISSUE THREAD

**Issue by petzi53** [jbub/ghostwriter#38]
Thank you for this wonderful theme: simple but very functional! I am relatively new to Hugo so I have some questions:

- the name of the author in the header of .md files does not work for me. The theme takes always the name I have put in under [Author] in the config.toml. It overwrites all names in the headers in the .md files.

- project files do not have authors. Is this intended? I believe there it would more important than in the blog, as projects are normally done cooperatively and one should mention all participants.

- how can I change the slug? Is it always the filename? This means I have to create a post with a good filename in mind and later -- if I change the focus/subject of the title, what happens many times -- to rename title (easy) **and** the file name (not so easy). The file name IMHO Is not important for readers as it is not seen, but the URL should transport some idea about the content of the post).

- is there a place where I can get some information what variables and metadata in the header of the posts/projects of your theme are allowed? I would need some kind of a primer …

- and last not least: I was surprised that the live site generated a comment form by Disqus. I left the disqusShortname = "XXX", e.g. I did not provide my Disqus short name.

(I was using ghostwriter with blogdown 0.1, hugo 0.27.1 and employed it via GitHub with Netlify.)

**Comment by petzi53** [comment]
In the meanwhile, I delved into the Hugo documentation and managed to apply the necessary changes myself.

**Comment by jbub** [comment]
Sorry for not responding @petzi53, i was on holiday, feel free to open another issue if you feel theres something to be done to improve the theme :) Thank you!

**Comment by jbub** [comment]
hey @fzenoni i just pushed d40349f it should now get the author from the post front mattter and default to the author from the site config to maintain backwards compatibility. The same goes for the author profile url.

**Comment by fzenoni** [comment]
Thank you so much for your prompt reaction!

**Comment by Nelson-Gon** [comment]
Seems broken with the latest version.

**Comment by jbub** [comment]
@Nelson-Gon please open new issue with steps on how to reproduce, thanks

**Comment by Nelson-Gon** [comment]
Sorry, I should have stated that it works, only that one needs to specifically name the folder as "post" and not something else.
