### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by johnbwilliams** [jbub/ghostwriter#39]
Hi jbub - great theme!       I request for a few bits of additional functionality:

- LinkedIn per-post sharing   (needed in addition to Twitter & Facebook per-post sharing)

- Inclusion of a YAML-specified image in per-post share content (text only shares get little attention on social media!)    

- filtering view of  blog posts titles by category and/or tag

Please let me know what you think of these proposed features!

Thank you Jbub!!!

**Comment by jbub** [comment]
Hey @johnbwilliams, ill go over the feature requests :)

1. Linked in post sharing is already implemented, its just disabled by default for backwards compatibility, you just need to set `shareLinkedIn = true` in your config.
2. Interesting idea, ill do some research how other themes are handling post images, have you seen any other themes that implement this ?
3. Im not sure what do you mean by this, hugo already generates tags, categories, you just have to setup Taxonomies (https://gohugo.io/content-management/taxonomies/).

Thank you!

**Comment by johnbwilliams** [comment]
Hey @jbub,

I've had more time to gain experience with your truly excellent ghostwriter theme (my ghostwriter site: www.openemr.blog).   I'd like to work with you to make ghostwriter even better!   Would it be possible to implement these features in ghostwriter?

1. Social media sharing of individual posts is working much better, thank you!   However, it is very important to include a meme image when sharing the top level of a ghostwriter site (i.e., sharing www.openemr.blog, not an individual post).   Would it be possible to specify a meme image in config.toml  for top level social media sharing?              

2. Is it possible to apply CSS styling to a Ghostwriter site?    

Thanks very much for your advice,  jbub, and I look forward to working with you to make Ghostwriter even better than it already is!    

Cheers!
John Williams

**Comment by rainsurf** [comment]
Not sure if this is the right place, but just wanted to say this is a fantastic theme! 👍

**Comment by jbub** [comment]
1. Hey @johnbwilliams, sorry i did not really have the time to look into that image thing. 
2. Regarding the styles question, yes this is mentioned in the Development 
section of the README https://github.com/jbub/ghostwriter#development.
3. Thanks @rainsurf, it really helps :)

**Comment by sofuca** [comment]
Hello, A feature I'd like is to be able to have different sections for blog posts. So clicking on each

`[[menu.main]]` would take you to that menu's blog posts.. is this possible?
