### ISSUE TITLE
How to change the number of post title per page.

### ISSUE THREAD

**Issue by weaming** [jbub/ghostwriter#4]
How to change the number of post title per page.

**Comment by jbub** [comment]
hello, what do you mean by number ?

**Comment by weaming** [comment]
Yes, it's my mean.
But what's  the meaning of `(where .Data.Pages "Type" "post")`?
Why just add a number after it can works?

**Comment by jbub** [comment]
It is mentioned in the documentation under the "List the pages" section (https://gohugo.io/extras/pagination/#list-the-pages): 

> The global page size setting (Paginate) can be overridden by providing a positive integer as the last argument.

**Comment by weaming** [comment]
Thanks for your reply.
