### ISSUE TITLE
Switch to chroma for code syntax highlighting

### ISSUE THREAD

**Issue by jbub** [jbub/ghostwriter#41]
- Drop support for https://highlightjs.org/
- https://gohugo.io/content-management/syntax-highlighting/

**Comment by kandelvijaya** [comment]
I think this is much needed. I have hard time configuring highlight.js.

**Comment by mthmulders** [comment]
Is there anything I could do to help on this issue? I see there's already a PR (thanks, @SteveLane!) so doing another one probably doesn't make sense... ;-)

**Comment by jbub** [comment]
Hey all, i have recently started working on this one, i want to make the transition as backwards compatible as possible :)

**Comment by geongeorge** [comment]
Can someone help me how to manually switch to chroma?
