### ISSUE TITLE
Editing the homepage

### ISSUE THREAD

**Issue by tiernanmartin** [jbub/ghostwriter#53]
Editing `layouts/index.html` does not result in changes to the site's homepage but edits made to `layouts/_default/list.html` do.

Is there a way to change this so that I can control the homepage by editing `layouts/index.html`?

**Comment by jbub** [comment]
That should not be the case, see https://gohugo.io/templates/lookup-order/. If you still have troubles please open another issue with example so that i can look :) Thank you!
