### ISSUE TITLE
Inconsistent highlighting inside code box

### ISSUE THREAD

**Issue by jethroppaPH** [jbub/ghostwriter#57]
I am using this theme in my [blog](jethroemmanuel.netlify.com). But I noticed that the highlighting inside the code box are not consistent. See one of my posts with the said issue [here](https://jethroemmanuel.netlify.com/2018/05/30/plot-pie-chart-tuna-landed-catch-map-in-r/).

**Screenshots**:

Screenshot 1:
![screenshot-1](https://user-images.githubusercontent.com/36062097/40818730-297cff7a-658b-11e8-9e24-2724e6fdb772.png)

Screenshot 2:
![screenshot-2](https://user-images.githubusercontent.com/36062097/40818733-2f74e28a-658b-11e8-9277-47e5c7db6c2c.png)

**Comment by jbub** [comment]
Hello, i assume this is the source code for the example post is this: https://gitlab.com/jethroppaPH/jethroemmanuel-ghostwriter/blob/master/content/post/2018-05-30-plot-pie-charts-of-tuna-landed-catch-composition-on-a-map-in-r.Rmd. 

By looking at it, you are not specifying the language type for the code highlighter. If you do not specify it, its going to guess and it might guess wrong. You can specify the type for the highlighter like this:

https://gist.githubusercontent.com/jbub/7e3bc28706f9cdb630c5b08a11a4c063/raw/211f2885824ef6e2ee9751abe0394942abdbbfb0/hugohighlight.md

**Comment by jethroppaPH** [comment]
I am currently away from my work station. I will try when I came back. BTW, where should I put that code?

**Comment by jethroppaPH** [comment]
Okay, so it means that I will put something like that in every code block?

**Comment by jbub** [comment]
Yes based on the code block language, so that the highlighter correctly highlights given code block.

**Comment by majvdvel** [comment]
We (@fzenoni and I) were following this discussion since we have the same issue on our blog. However the proposed fix is logical for normal markdown files, as stated in the R markdown documentation (https://rmarkdown.rstudio.com/lesson-2.html), it should parse without an additional language in front of the curly braces-enclosed language. So is it advised to rewrite all R markdown files into a markdown format? (Which in my opinion is rather silly)

**Comment by jbub** [comment]
Hey all,

Either you put the language code in there and help the highlighter or you do not and its going to try to autodetect the language - and as you can see it might be wrong.

Here are some workarounds im thinking about:

1. You can preprocess the rmarkdown files and add the language code there in the build step before calling hugo, using `sed` or some regex replacing.
2. You can add some javascript that will add the needed css classes for the highlighter. This is the highlighter https://highlightjs.org/

**Comment by jethroppaPH** [comment]
Hi. This is what I did:

I add the following lines in the `layouts/partials/extra-in-head.html` located at the root of my project:

```
<head>
  {{ with .Site.Params.highlightjs }}
  <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/{{ . }}.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  {{ range $.Site.Params.highlightjs_extra_languages }}
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/{{ . }}.min.js"></script>
  {{ end }}
  <script>hljs.initHighlightingOnLoad();</script>
  {{ end }}

</head>
```

And in my `config.toml` I add the following lines under the `[params]`:

```
    highlightjs = "monokai-sublime"
    highlightjs_extra_languages = ["r"]
```

And this is the result:

Screenshot 1:

![screenshot-3](https://user-images.githubusercontent.com/36062097/40846983-a5f56b66-65ed-11e8-8c21-558262d399a2.png)

Screenshot 2:

![screenshot-4](https://user-images.githubusercontent.com/36062097/40847008-b4580e84-65ed-11e8-9384-6d28c0d4e16c.png)

**Comment by jbub** [comment]
By the way, we plan to Switch to Chroma at some point and remove the highlight.js dependency. Can someone try if Chroma does a better job of autodetecting R code snippets ?

**Comment by schochastics** [comment]
For blogdown user still having this issue: 
The approach described [here](https://notast.netlify.com/post/adding-syntax-highlight/) under "blogdown textbook approach" worked for me

**Comment by jbub** [comment]
Chroma is implemented, this is not relevant anymore, im closing this, thank you :)
