### ISSUE TITLE
Tag Display Inconsistencies

### ISSUE THREAD

**Issue by madsolar8582** [jbub/ghostwriter#58]
I've noticed that if you create a page that displays all of the tags of your posts, there isn't a way to control the format of the list of tags (i.e. all uppercase/lowercase or as entered). Additionally, if you have a lot of tags, the page navigation between the pages references posts instead of tags.

I think it would be beneficial to allow for the tag display to be customized so that the case is uniform and for the navigation to say tags instead of posts.

Example:
![tags](https://user-images.githubusercontent.com/408449/42137069-884c5cd2-7d2b-11e8-9b6f-35bac90764bf.PNG)

**Comment by jbub** [comment]
Hello, i have added the possibility to customize tag list page in fd753c3ed3ef3bad35681af001574a3b3964e272.
