### ISSUE TITLE
Get the about.md page as intro

### ISSUE THREAD

**Issue by k0pernicus** [jbub/ghostwriter#6]
Hello!
I'm trying to modify this beautiful theme to display in my homepage the content of `about.md`, contained in `content/about.md`.

If my intuition is correct, I have to update the `index.html` webpage.
But, even after reading the tutorial about Hugo templates, I don't understand how to ask to the `index.html` file: "Please, read the content of `about.md` when the path is `/`".
Can somebody help me please? :-/

Thanks a lot!

**Comment by jbub** [comment]
Hello, as you can see in the index.html file, it currently shows a list of posts. In order to show your about page instead you will have to update the index.html file. This forum thread should help you https://discuss.gohugo.io/t/homepage-content-from-content-home-md/54.
