### ISSUE TITLE
Don't hard-code the post section to "post"

### ISSUE THREAD

**Issue by kaushalmodi** [jbub/ghostwriter#60]
On [this line][1], you hard-code the post section to be called "post":

```
{{ $pag := .Paginate (where .Data.Pages "Type" "post") }}
```

It is not a good Hugo templating practice. Using the below is better:

```
{{ $pag := .Paginate (where .Pages "Type" "in" .Site.Params.mainSections) }}
```

[Reference][2]

/cc @JuanPabloMF

[1]: https://github.com/jbub/ghostwriter/blob/2340a01fea08ecfff62ee22551741180862156ce/layouts/index.html#L7
[2]: https://gohugo.io/functions/where/#portable-where-filters

**Comment by jbub** [comment]
Should be fixed by 6e9eabc9ce50c6240581fa2908c47b2cc0f2db95
