### ISSUE TITLE
Site not building in Netlify

### ISSUE THREAD

**Issue by letslearndevops** [jbub/ghostwriter#72]
`2:58:54 PM: Executing user command: hugo
2:58:54 PM: ERROR 2019/10/20 13:58:54 Failed to add template "partials/header.html" in path "partials/header.html": template: partials/header.html:10: function "hugo" not defined
2:58:54 PM: ERROR 2019/10/20 13:58:54 partials/header.html : template: partials/header.html:10: function "hugo" not defined
2:58:54 PM: Building sites …
2:58:54 PM: ERROR 2019/10/20 13:58:54 Error while rendering "page" in "post/": template: post/single.html:1:3: executing "post/single.html" at <partial "header.html...>: error calling partial: template: "partials/header.html" is an incomplete or empty template
2:58:54 PM: Skipping functions preparation step: no functions directory set`

**Comment by jbub** [comment]
You are probably runnning some old version of hugo, can you post your hugo version ?

**Comment by letslearndevops** [comment]
yes, that's correct - sorry!
