### ISSUE TITLE
Security issues with yarn.loc?

### ISSUE THREAD

**Issue by DataStrategist** [jbub/ghostwriter#73]
So everytime I update my blog, github has a ton of security complaints:
![image](https://user-images.githubusercontent.com/8094091/67565565-a1ab9680-f71d-11e9-8fb2-80b47885571d.png)

am I the only one? Or am I somehow missing a step?

**Comment by DataStrategist** [comment]
Sorry it seems most of those are old... just the `macaddress` seems to still be a problem. Check this out https://github.com/DataStrategist/amitkohli.com/pull/6

**Comment by jbub** [comment]
Hello, thanks for the report, i just enabled security alerts for this repository. Ill see what will pop up and then check it out. Will report back.

**Comment by jbub** [comment]
I have got an update, i just upgradet to webpack 4 in 60f58b53506385c548469ce2caa3ccca94d7f301 and the count of alerts dropped to just 4 now.

**Comment by jbub** [comment]
Ok i fixed what i could, those 4 remaining - we will have to wait for the upstream packages to fix themselves. Thank you!

**Comment by DataStrategist** [comment]
Hi @jbub please see this issue I opened in the main folder, does what he said help at all?

**Comment by jbub** [comment]
@DataStrategist you misunderstood my point, by upstream packages i meant those javascript packages i do not have control of.

**Comment by DzasterAbz** [comment]
@jbub & @DataStrategist , itseems like I could auto-patch with Github Bot. Only the "lodash" & "tar" are troubling. There is something wrong with the YARN. I tried something with NPM but it wasn't affecting. Maybe we have to migrate from YARN to NPM.

P.S. I am not a Web Developer. I read something online today about this. Pardon me if I am wrong.
