### ISSUE TITLE
Link to headers?

### ISSUE THREAD

**Issue by jarrodscott** [jbub/ghostwriter#74]
Hi. Awesome theme. Is there a way to include links to headers within a page? Thanks!

**Comment by jbub** [comment]
Hello @jarrodscott what do you mean by headers ?

**Comment by jarrodscott** [comment]
hello @jbub 

Sorry for not being more clear. 
For example, if I have something like this somewhere in a post:

```
## Header 1

Some text....

## Header 2

More text...
```

What I would link to do is add an `anchorjs-link` to each header. [This page](https://istmobiome.rbind.io/projects/trans-water/2-2-annotation-summary/) has an example of what I mean.

I am probably using some of the terminology incorrectly but I hope this makes more sense. What I am not sure about is whether this is a feature I can add to the theme or not. Thanks for your help.

**Comment by jbub** [comment]
Ah i see, do you know of any other Hugo templates that support this ? I mean hugo already generates ids for headers, we would just have to add the classes right ?

**Comment by jarrodscott** [comment]
The only other theme I have much experience with is [Hugo Academic](https://github.com/gcushen/hugo-academic) which is where I got the idea. I am doing some digging now and will let you know what I find. I'm a bit new to Hugo :)

**Comment by jbub** [comment]
Okay keep me posted :)

**Comment by jarrodscott** [comment]
Ok, I made some progress. 

I found some code [here](https://discourse.gohugo.io/t/best-practice-adding-link-to-heading/13698/3) and put it in a partial called `links.html` exactly like this.
```
{{- with .Content -}}
<div itemid="articleBody">
 {{ . | replaceRE "(<h[1-9] id=\"([^\"]+)\".+)(</h[1-9]+>)" `${1}<a href="#${2}" class="hanchor" ariaLabel="Anchor"> 🔗&#xFE0E;</a> ${3}` | safeHTML }}
</div>
{{- end -}}
```

I then tried putting this line ` {{ partial "links.html" . }}` in the `page/single.html`.  I tried several places in the file. It worked, i.e. headers with links. The problem is that I get a duplicate copy of the the entire content of the page. One part has links the other doesn't. 

For example, if I do this:

```
{{ partial "header.html" . }}

<div class="container">
    <article class="post-container">
        {{ partial "links.html" . }}

        {{ partial "page-header.html" . }}

        {{ partial "page-content.html" . }}
    </article>
</div>

{{ partial "footer.html" . }}
```
I get this:

<img width="945" alt="Screen Shot 2020-03-30 at 3 24 02 PM" src="https://user-images.githubusercontent.com/16192182/77958393-97786000-729a-11ea-90fd-cfae189daf1d.png">

I have tried to place `{{ partial "links.html" . }}` in different locations but it always causes something like this to happen. So close!

**Comment by jarrodscott** [comment]
I'm a little slow. Pretty sure `{{- with .Content -}}` is whats causing the doubling. I have another idea. More soon

**Comment by jarrodscott** [comment]
Got it to work for pages by adding code to the  `page-content.html` partial. Final version looks like this.

```
<div class="post-content clearfix" itemprop="articleBody">
    {{ with .Params.Image }}
        <img class="post-featured-image" src="{{ . }}">
    {{ end }}

    {{ with  .Content }}
      <div itemid="articleBody">
        {{ . | replaceRE "(<h[1-9] id=\"([^\"]+)\".+)(</h[1-9]+>)" `${1}<a href="#${2}" class="hanchor" ariaLabel="Anchor"> 🔗&#xFE0E;</a> ${3}` | safeHTML }}
      </div>
    {{ end }}
</div>
```

Still cannot get it to work with `post-content`

**Comment by jbub** [comment]
Nice job, im going to close this one.
