### ISSUE TITLE
Change main page

### ISSUE THREAD

**Issue by tauanajc** [jbub/ghostwriter#76]
Dear Juraj, thanks for the theme.
I am trying to change the content of the main page of a website with ghostwriter. I noticed the main page has the content under 'post', but I would like that to be only under one of the other main menus (in my case, I have a main menu called tutorials where I will have the posts).
But I don't know how to change that in the config file. I would like the front page of the site to be a page called Home, which could be the main menu with weight 1, and add some blurb there, but not posts. Where can I put some markdown text to go in the initial page?
Hope it's not too confusing.
Thanks!

**Comment by tauanajc** [comment]
Ok, I found that I can edit the index.html file under themes/ghostwriter/layout/ to include text in the front page, while also maintaining the 'posts' there. It's not exactly what I was looking for, but I think this is how this theme/design is supposed to be, and I am happy with the result right now. Thanks

**Comment by jbub** [comment]
Hello im glad you resolved it :)
