### ISSUE TITLE
Remove 'feed' icon on front page?

### ISSUE THREAD

**Issue by tauanajc** [jbub/ghostwriter#77]
Hi there,
I can't find where in the theme we can edit the little 'feed' icon that seats right on the top center of the website. Whenever I click on it, it opens the News app on my mac. I have no use for it and would like to remove it completely, but don't know how. Thanks in advance.

**Comment by jbub** [comment]
Hello if you mean the RSS button we currently do not have a way to disable it, you would have override the whole layouts/partials/header.html which is not great. But yeah i should make this configurable.

**Comment by dylanhthomas** [comment]
I made this change. I'll submit a pull request
