### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by DzasterAbz** [jbub/ghostwriter#79]
### Github Security has discovered 5 serious vulnerability issues.
- **acorn**
Current Version: **6.4.0**
Remediation: Upgrade acorn to version **6.4.1** or above.

- **fstream**
Current Version: **1.0.10**
Remediation: Upgrade fstream to version **1.0.12** or above.

- **tar**
Current Version: **< 2.2.0**
Remediation: Upgrade tar to version **2.2.2** or above.

- **sshpk**
Current Version: **1.10.1**
Latest Version: **1.16.1**
Remediation: Upgrade sshpk to version **1.13.2** or above. 

- **lodash**
Current Version: **< 4.17.12** 
Remediation: Upgrade lodash to version **4.17.12** or above.

Don't know if it's everyone or just me facing this issue.

**Comment by jbub** [comment]
Please see #73.
