### ISSUE TITLE
Move CSS/JS files to assets folder, use pipes, remove dist folder

### ISSUE THREAD

**Issue by LikiPiki** [jbub/ghostwriter#82]
Hello, thanks a lot for porting this theme to Hugo!

I found the dist folder in this repo. It's not a good solution in Hugo, I suggest to use Hugo pipes and remove the "dist" folder, it's a more clean and good solution to override code and make CSS/JS chunks, without editing theme files inside and rebuild with yarn.

More about Hugo pipes you can find here - https://regisphilibert.com/blog/2018/07/hugo-pipes-and-asset-processing-pipeline/

I can do refactoring and help with it! Waiting for your feedback. Thx!

**Comment by jbub** [comment]
Hello thanks for the info, i know about the SCSS pipes, but i dont want this theme to depend on Gugo extended build (which requires CGO and C compiler).

**Comment by LikiPiki** [comment]
Thx for the fast reply. Not a problem. I fork your repo and try to use assets in my case.

**Comment by jbub** [comment]
Hopefully there will be Pure Go SCSS library soon :)
