### ISSUE TITLE
Cannot activate menu system through config file

### ISSUE THREAD

**Issue by mdasfour** [jbub/ghostwriter#98]
Hello,

I have been trying to use the menu system for the ghostwriter theme with no success.  I have followed the example in the ```config.yml```, but have placed square brackets around the name of the parameter since this is how it works with when using ```config.toml``` file for Netlify.  This is how I did it and it did not work:
```
[menu]
  [main]
     name: "Blog"
      url: "/"
      weight: 1
```
How would I go about implementing the menu system correctly?

Thanks

**Comment by jbub** [comment]
Hey @mdasfour 

this should be the way to do in TOML:

```
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
```

**Comment by mdasfour** [comment]
Hi @jbub,

This is very helpful.  I have been trying to figure out how to make this work.  I appreciate it.

Thanks.

:)

**Comment by jbub** [comment]
No problem :)
